---
title: "Prepare UK BioBank Data Lung"
output: html_notebook
---

Read in the raw stat UK Biobank file. 

```{r}

UKBiobank <- read.csv("/Users/teresanguyen/Downloads/CleaningLungData/Data Files/rawStatBioUKB.csv", 
                      as.is = TRUE)
head(UKBiobank)
dim(UKBiobank)
colnames(UKBiobank)

```

Processing Data

```{r}

processUKBData <- function(DataFile) {
  
  # age
  age <- DataFile$X21022.0.0
  DataFile$age <- (DataFile$X21022.0.0 / 100)
  
  # One hot encoding race
  plco_field <- 'race7'
  DataFile[[plco_field]] <- 7
  plco_codes <- c(1, 2, 4)
  ukbb_codes <- list(c(1, 1001, 1002, 1003), c(2001, 2002, 4002, 4003, 4, 4001),
                     c(3001, 3002, 2003, 3, 3003, 3004, 5))
  instances <- c('0.0', '1.0', '2.0')

  for (instance in instances) {
    for (i in seq_along(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X21000.', instance)]] == old_code & DataFile[[plco_field]] == 7)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }

  DataFile$raceWh <- DataFile[[plco_field]] == 1
  DataFile$raceBl <- DataFile[[plco_field]] == 2
  DataFile$raceHis <- DataFile[[plco_field]] == 3
  DataFile$raceAs <- DataFile[[plco_field]] == 4
  DataFile$racePI <- DataFile[[plco_field]] == 5
  DataFile$raceAI <- DataFile[[plco_field]] == 6
  DataFile$raceMis <- DataFile[[plco_field]] == 7

  # One hot encoding education level
  plco_field <- 'education'
  DataFile[[plco_field]] <- 9
  plco_codes <- c(3, 4, 5, 6)
  ukbb_codes <- list(c(3, 4), c(6), c(2, 5), c(1))
  instances <- c('0.0', '1.0', '2.0', '3.0',
                 '0.1', '1.1', '2.1', '3.1',
                 '0.2', '1.2', '2.2', '3.2',
                 '0.3', '1.3', '2.3', '3.3',
                 '0.4', '1.4', '2.4', '3.4',
                 '0.5', '1.5', '2.5', '3.5')
  
  for (instance in instances) {
    for (i in seq_along(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X6138.', instance)]] == old_code & DataFile[[plco_field]] == 9)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  DataFile$edlt8 <- DataFile[[plco_field]] == 1
  DataFile$ed8t11 <- DataFile[[plco_field]] == 2
  DataFile$ed12 <- DataFile[[plco_field]] == 3
  DataFile$edphs <- DataFile[[plco_field]] == 4
  DataFile$edscol <- DataFile[[plco_field]] == 5
  DataFile$edcol <- DataFile[[plco_field]] == 6
  DataFile$edpcol <- DataFile[[plco_field]] == 7
  
  # One hot encoding: marriage
  plco_field <- 'marriage'
  DataFile[[plco_field]] <- 9
  plco_codes <- c(1)
  ukbb_codes <- list(c(1))
  instances <- c('0.0', '1.0', '2.0', '3.0',
                 '0.1', '1.1', '2.1', '3.1',
                 '0.2', '1.2', '2.2', '3.2',
                 '0.3', '1.3', '2.3', '3.3',
                 '0.4', '1.4', '2.4', '3.4')
  
  for (instance in instances) {
    for (i in seq_along(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X6141.', instance)]] == old_code & DataFile[[plco_field]] == 9)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  DataFile$marmar <- DataFile[[plco_field]] == 1
  DataFile$marwid <- DataFile[[plco_field]] == 2
  DataFile$mardiv <- DataFile[[plco_field]] == 3
  DataFile$marsep <- DataFile[[plco_field]] == 4
  DataFile$marnvm <- DataFile[[plco_field]] == 5

  # One hot encoding: occupation
  plco_field <- 'occupat'
  DataFile[[plco_field]] <- 9
  plco_codes <- c(1, 2, 3, 4, 6, 7)
  ukbb_codes <- list(c(3), c(1), c(5), c(2), c(4), c(6, 7))
  instances <- c('0.0', '1.0', '2.0', '3.0',
                 '0.1', '1.1', '2.1', '3.1',
                 '0.2', '1.2', '2.2', '3.2',
                 '0.3', '1.3', '2.3', '3.3',
                 '0.4', '1.4', '2.4', '3.4',
                 '0.5', '1.5', '2.5', '3.5',
                 '0.6', '1.6', '2.6', '3.6')
  
  for (instance in instances) {
    for (i in seq_along(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X6142.', instance)]] == old_code & DataFile[[plco_field]] == 9)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  DataFile$occhmk <- DataFile[[plco_field]] == 1
  DataFile$occwrk <- DataFile[[plco_field]] == 2
  DataFile$occune <- DataFile[[plco_field]] == 3
  DataFile$occret <- DataFile[[plco_field]] == 4
  DataFile$occesl <- DataFile[[plco_field]] == 5
  DataFile$occdis <- DataFile[[plco_field]] == 6
  DataFile$occoth <- DataFile[[plco_field]] == 7
  
  cat("Done with demographics\n")
  
  # bmi_curr
  plco_field <- 'bmi_curr'
  DataFile[[plco_field]] <- NA
  plco_codes <- c(1, 2, 3, 4)
  # had to remove 1.0, 2.0, 3.0 because the data frame did not match
  instances <- c('0.0')
  
  for (instance in instances) {
    idx <- is.na(DataFile[[plco_field]])
    DataFile[idx, plco_field] <- DataFile[[paste0('X21001.', instance)]]
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 100
  
  
  # UK Biobank doesn't have weight at 20
  plco_field <- 'weight20_f'
  DataFile[[plco_field]] <- NA
  
  # arthrit_f
  plco_field <- 'arthrit_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(
    c(),
    c('M0000','M0001','M0002','M0003','M0005','M0006','M0007','M0008','M0009',
      'M0010','M0012','M0016',
      'M0020','M0021','M0023','M0024','M0025','M0026','M0027','M0028','M0029',
      'M0080','M0081','M0085','M0086','M0087',
      'M0090','M0091','M0092','M0093','M0094','M0095','M0096','M0097','M0098','M0099',
      'M0107',
      'M011',
      'M0139',
      'M0150',
      'M0186','M0187','M0189',
      'M0500','M0509',
      'M0510','M0517','M0518','M0519',
      'M0520','M0524','M0526','M0528','M0529',
      'M0530','M0538','M0539',
      'M0580','M0582','M0583','M0584','M0586','M0587','M0588','M0589',
      'M0590','M0591','M0592','M0593','M0594','M0595','M0596','M0597','M0598','M0599',
      'M0600','M0601','M0602','M0603','M0604','M0605','M0606','M0607','M0608','M0609',
      'M0610','M0611','M0616','M0619',
      'M0621','M0622','M0625','M0626','M0627',
      'M0630','M0632','M0633','M0634','M0636','M0637','M0638','M0639',
      'M0640','M0641','M0643','M0644','M0645','M0646','M0647','M0649',
      'M0680','M0681','M0682','M0684','M0685','M0686','M0687','M0688','M0689',
      'M0690','M0691','M0692','M0693','M0694','M0695','M0696','M0697','M0698','M0699',
      'M0717','M0719',
      'M0800','M0802','M0804','M0805','M0806','M0807','M0808','M0809',
      'M0810','M0819',
      'M0820','M0822','M0825','M0826','M0827','M0828','M0829',
      'M0830','M0836','M0839',
      'M0840','M0844',
      'M0880',
      'M0890','M0896','M0899',
      'M0909',
      'M1300','M1301','M1303','M1304','M1305','M1306','M1307','M1308','M1309',
      'M1310','M1311','M1312','M1313','M1314','M1315','M1316','M1317','M1319',
      'M1380','M1381','M1382','M1383','M1384','M1385','M1386','M1387','M1388','M1389',
      'M1390','M1391','M1392','M1393','M1394','M1395','M1396','M1397','M1398','M1399')
  )
  cond_len <- 213
  
  for (instance in 1:cond_len) {
    for (i in seq_along(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  # bronchit_f
  plco_field <- 'bronchit_f'
  DataFile[[plco_field]] <- NA
  
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(0), c(1))
  
  instances <- c('0.0')
  
  for(instance in instances) {
    for(i in seq_along(plco_codes)) {
      new_code <- plco_codes[i]
      for(old_code in ukbb_codes[[i]]) {
        col_name <- paste('X22129.', instance, sep = "")
        
        idx <- which(DataFile[[col_name]] == old_code & is.na(DataFile[[plco_field]]))
        
        DataFile[idx, plco_field] <- new_code
      }
    }
  }

  # colon_comorbidity
  plco_field <- 'colon_comorbidity'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('K510','K511','K512','K513','K514','K515','K518','K519','K500','K501','K508','K509'))
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[['X41270.0.', as.character(instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  # Diabetes
  DataFile$diabetes_f <- ifelse(DataFile$X2443.0.0 %in% c(-1,-3), NA, DataFile$X2443.0.0)
  DataFile$diabetes_f <- as.numeric(DataFile$diabetes_f)
  unique(DataFile$X2443.0.0)
  
  # divertic
  plco_field <- 'divertic_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('K570','K571','K572','K573','K574','K575','K578','K579'))
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  # Emphysema
  plco_field <- 'emphys_f'
  DataFile[[plco_field]] <- NA
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(0), c(1))
  instances <- c('0.0')
  
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X22128.', instance)]] == old_code & is.na(DataFile[[plco_field]]))
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  # Gallbladder
  plco_field <- 'gallblad_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(character(0), c('K800','K801','K802','K803','K8036','K804','K805','K808','K810','K811','K818','K819'))
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  # hearta_f
  plco_field <- 'hearta_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(character(0), c('I050','I051','I052', 'I058', 'I059','I090','I091','I098','I099','I110','I119','I130','I131','I132','I139','I120','I201','I208','I209','I210','I211','I212','I213','I214','I219','I220','I221','I228','I229','I240','I241','I248','I249','I250','I251','I252','I253','I254','I255','I256','I258','I259'))
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  # hypertension
  plco_field <- 'hyperten_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(character(0), 'I10')
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      old_code <- ukbb_codes[[i]]
      idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
      DataFile[idx, plco_field] <- new_code
    }
  }
  
  # Liver Comorbidity
  plco_field <- 'liver_comorbidity'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(character(0), c('B159','B160','B169','B170','B171','B172','B178','B179','B180','B181','B182','B188','B189','B199','K703','K717','K740','K741','K742','K743','K744','K745','K746'))
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('41270-0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  # Osteoporosis
  plco_field <- 'osteopor_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(character(0), c('M8000','M8001','M8003','M8005','M8007','M8008','M8009','M8010','M8021','M8025','M8028','M8040','M8041','M8046','M8048','M8049','M8050','M8052','M8053','M8055','M8058','M8080','M8081','M8082','M8085','M8086','M8087','M8088','M8089','M8090','M8091','M8092','M8093','M8094','M8095','M8096','M8097','M8098','M8099','M8100','M8102','M8105','M8108','M8109','M8110','M8119','M8120','M8129','M8130','M8138','M8139','M8140','M8143','M8144','M8145','M8147','M8148','M8149','M8150','M8151','M8155','M8158','M8159','M8165','M8167','M8168','M8169','M8180','M8185','M8187','M8188','M8189','M8190','M8191','M8192','M8193','M8194','M8195','M8196','M8197','M8198','M8199','M8200','M8201','M8206','M8208','M8209','M8210','M8211','M8213','M8218','M8219'))
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  # Colorectal Polyps
  plco_field <- 'polyps_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(character(0), c('K620','K621','K635'))
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }

  # Stroke
  plco_field <- 'stroke_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(character(0), c('G463','G464','I64','I694'))
  
  for (instance in 1:cond_len) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
      }
    }
  }
  
  cat("Starting Smoking Questions\n")
  
  # Ever smoked
  plco_field <- 'smoked_f'
  DataFile[[plco_field]] <- NA
  plco_codes <- c(0, 1)
  ukbb_codes <- list(0, 1)
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      old_code <- ukbb_codes[i]
      idx <- which(DataFile[[paste0('X20160.', instance)]] == old_code & is.na(DataFile[[plco_field]]))
      DataFile[idx, plco_field] <- new_code
    }
  }

  # Current Smoker
  # 0 to Never | 1 is previous | 2 is current | -3 is prefer not to answer NA
  DataFile$X20116.0.0[DataFile$X20116.0.0 == "-3"] <- NA
  DataFile$X20116.0.0[DataFile$X20116.0.0 == "1"] <- 0.5
  DataFile$X20116.0.0[DataFile$X20116.0.0 == "2"] <- 1
  DataFile$cig_stat <- DataFile$X20116.0.0
  
  # Number of years since they stopped smoking
  DataFile$X6194.0.0[DataFile$X6194.0.0 == -1] <- NA
  
  # Perform the calculation only when both age and X6194.0.0 are not NA
  valid_indices <- !is.na(DataFile$X6194.0.0)
  DataFile$cig_stop <- NA
  DataFile$cig_stop[valid_indices] <- DataFile$X21022.0.0[valid_indices] - DataFile$X6194.0.0[valid_indices]
  DataFile$cig_stop <- DataFile$cig_stop / 100
  
  # Number of pack years smoked
  plco_field <- 'pack_years'
  DataFile[[plco_field]] <- NA
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    idx <- is.na(DataFile[[plco_field]])
    DataFile[idx, plco_field] <- DataFile[[paste0('X20161.', instance)]][idx]
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 500
  
  # aspirin
  # Replace -1 and -3 with NA, and values other than 1 with 0
  # UKBiobank only has if it is taken regularly --> room for improvement as we can use "asp" instead for PLCO
  
  # DataFile$asppd <- ifelse(DataFile$X6154.0.0 %in% c("-1", "-3"), NA, 
  #                             ifelse(DataFile$X6154.0.0 != "1", "0", DataFile$X6154.0.0))
  # 
  # DataFile[[plco_field]] <- DataFile[[plco_field]] / 60
  
  DataFile$asppd <- 0
  
  plco_codes <- c(1, 9)
  ukbb_codes <- list(c(1), c(-1, -3))
  
    instances <- c('0.0')
    for(instance in instances) {
    for(i in seq_along(plco_codes)) {
      new_code <- plco_codes[i]
      for(old_code in ukbb_codes[[i]]) {
        col_name <- paste('X6154.', instance, sep = "")
        
        idx <- which(DataFile[[col_name]] == old_code & DataFile$asppd == 9)
        
        DataFile$asppd[idx] <- new_code
      }
    }
  }
  
  DataFile$asppd <- DataFile$asppd / 60

  
  
  # ibuprofen
  # UKBiobank only has if it is taken regularly --> room for improvement as we can use "ibup" instead for PLCO
  # Replace -1 and -3 with NA, and values other than 2 with 0
  # DataFile$ibuppd <- ifelse(DataFile$X6154.0.0 %in% c("-1", "-3"), NA, 
  #                           ifelse(DataFile$X6154.0.0 != "2", "0", DataFile$X6154.0.0))
  
  # Define the initial settings for the field in the data frame
  plco_field <- 'ibuppd'
  DataFile[[plco_field]] <- 0
  
  # Define the PLCO and UKBB codes
  plco_codes <- c(1, 9)
  ukbb_codes <- list(c(2), c(-1, -3))
  
  # List of instances to iterate over
  instances <- c('0.0')
  
  # Loop through each instance and codes to update the DataFile data frame
  for(instance in instances) {
    for(i in seq_along(plco_codes)) {
      new_code <- plco_codes[i]
      for(old_code in ukbb_codes[[i]]) {
        # Construct the column name
        col_name <- paste('X6154.', instance, sep = "")
        
        # Identify rows where conditions are met and update the data frame
        idx <- which(DataFile[[col_name]] == old_code & DataFile[[plco_field]] == 9)
        DataFile[[plco_field]][idx] <- new_code
      }
    }
  }
  
  # Adjust the plco_field by dividing each entry by 60
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 60

  
  # Family History
  
  cat("Starting Family History\n")
  
  # family history of prostate cancer
  plco_field <- 'pros_fh'
  DataFile[[plco_field]] <- 0
  DataFile[[paste0(plco_field, '_age')]] <- NA
  DataFile[[paste0(plco_field, '_cnt')]] <- 0
  plco_codes <- c(1, 9)
  ukbb_codes <- list(13, c(-11, -13, -21, -23))
  instances <- c('0.0', '1.0', '2.0', '3.0',
                 '0.1', '1.1', '2.1', '3.1',
                 '0.2', '1.2', '2.2', '3.2',
                 '0.3', '1.3', '2.3', '3.3',
                 '0.4', '1.4', '2.4', '3.4',
                 '0.5', '1.5', '2.5', '3.5',
                 '0.6', '1.6', '2.6', '3.6',
                 '0.7', '1.7', '2.7', '3.7',
                 '0.8', '1.8', '2.8', '3.8',
                 '0.9', '1.9', '2.9', '3.9')
  
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20107.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20110.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  instances <- c('0.10', '1.10', '2.10', '3.10')
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20110.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  instances <- c('0.11', '1.11', '2.11', '3.11')
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  DataFile[DataFile[[plco_field]] == 9, paste0(plco_field, '_cnt')] <- NA
  DataFile[DataFile[[plco_field]] == 9, plco_field] <- NA
  DataFile[[paste0(plco_field, '_cnt')]] <- DataFile[[paste0(plco_field, '_cnt')]] / 10
  
  # Family history of breast cancer
  plco_field <- 'breast_fh'
  DataFile[[plco_field]] <- 0
  DataFile[[paste0(plco_field, '_age')]] <- NA
  DataFile[[paste0(plco_field, '_cnt')]] <- 0
  plco_codes <- c(1, 9)
  ukbb_codes <- list(5, c(-11, -13, -21, -23))
  instances <- c('0.0', '1.0', '2.0', '3.0',
                 '0.1', '1.1', '2.1', '3.1',
                 '0.2', '1.2', '2.2', '3.2',
                 '0.3', '1.3', '2.3', '3.3',
                 '0.4', '1.4', '2.4', '3.4',
                 '0.5', '1.5', '2.5', '3.5',
                 '0.6', '1.6', '2.6', '3.6',
                 '0.7', '1.7', '2.7', '3.7',
                 '0.8', '1.8', '2.8', '3.8',
                 '0.9', '1.9', '2.9', '3.9')
  
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20107.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20110.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  instances <- c('0.10', '1.10', '2.10', '3.10')
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20110.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  instances <- c('0.11', '1.11', '2.11', '3.11')
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  DataFile[DataFile[[plco_field]] == 9, paste0(plco_field, '_cnt')] <- NA
  DataFile[DataFile[[plco_field]] == 9, plco_field] <- NA
  DataFile[[paste0(plco_field, '_cnt')]] <- DataFile[[paste0(plco_field, '_cnt')]] / 10
  
  # family history of bowel cancer
  plco_field <- 'colo_fh'
  DataFile[[plco_field]] <- 0
  DataFile[[paste0(plco_field, '_age')]] <- NA
  DataFile[[paste0(plco_field, '_cnt')]] <- 0
  plco_codes <- c(1, 9)
  ukbb_codes <- list(4, c(-11, -13, -21, -23))
  instances <- c('0.0', '1.0', '2.0', '3.0',
                 '0.1', '1.1', '2.1', '3.1',
                 '0.2', '1.2', '2.2', '3.2',
                 '0.3', '1.3', '2.3', '3.3',
                 '0.4', '1.4', '2.4', '3.4',
                 '0.5', '1.5', '2.5', '3.5',
                 '0.6', '1.6', '2.6', '3.6',
                 '0.7', '1.7', '2.7', '3.7',
                 '0.8', '1.8', '2.8', '3.8',
                 '0.9', '1.9', '2.9', '3.9')
  
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20107.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20110.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  instances <- c('0.10', '1.10', '2.10', '3.10')
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20110.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  instances <- c('0.11', '1.11', '2.11', '3.11')
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  DataFile[DataFile[[plco_field]] == 9, paste0(plco_field, '_cnt')] <- NA
  DataFile[DataFile[[plco_field]] == 9, plco_field] <- NA
  DataFile[[paste0(plco_field, '_cnt')]] <- DataFile[[paste0(plco_field, '_cnt')]]/10
  
  # family history of lung cancer
  plco_field <- 'lung_fh'
  DataFile[[plco_field]] <- 0
  DataFile[[paste0(plco_field, '_age')]] <- NA
  DataFile[[paste0(plco_field, '_cnt')]] <- 0
  plco_codes <- c(1, 9)
  ukbb_codes <- list(3, c(-11, -13, -21, -23))
  instances <- c('0.0', '1.0', '2.0', '3.0',
                 '0.1', '1.1', '2.1', '3.1',
                 '0.2', '1.2', '2.2', '3.2',
                 '0.3', '1.3', '2.3', '3.3',
                 '0.4', '1.4', '2.4', '3.4',
                 '0.5', '1.5', '2.5', '3.5',
                 '0.6', '1.6', '2.6', '3.6',
                 '0.7', '1.7', '2.7', '3.7',
                 '0.8', '1.8', '2.8', '3.8',
                 '0.9', '1.9', '2.9', '3.9')
  
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20107.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20110.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  instances <- c('0.10', '1.10', '2.10', '3.10')
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20110.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  instances <- c('0.11', '1.11', '2.11', '3.11')
  for (instance in instances) {
    for (i in 1:length(plco_codes)) {
      new_code <- plco_codes[i]
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X20111.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[idx, plco_field] <- new_code
        if (new_code == 1) {
          DataFile[idx, paste0(plco_field, '_cnt')] <- DataFile[idx, paste0(plco_field, '_cnt')] + 1
        }
      }
    }
  }
  
  DataFile[DataFile[[plco_field]] == 9, paste0(plco_field, '_cnt')] <- NA
  DataFile[DataFile[[plco_field]] == 9, plco_field] <- NA
  DataFile[[paste0(plco_field, '_cnt')]] <- DataFile[[paste0(plco_field, '_cnt')]]/10
  
  cancers <- c('bili','blad','endo','glio','hnc','hema','liver','mbreast','mela',
               'ovarsumm','panc','renal','thyd','upgi')
  for (cancer in cancers) {
    DataFile[[paste0(cancer, '_fh')]] <- NA
    DataFile[[paste0(cancer, '_fh_age')]] <- NA
    DataFile[[paste0(cancer, '_fh_cnt')]] <- NA
  }
  
  cancers <- c('bili','blad','breast','colo','endo','glio','hnc','hema','liver',
               'lung','mbreast','mela','osumm','panc','pros','renal','thyd','upgi')
  for (cancer in cancers) {
    DataFile[[paste0('trial_ph_', cancer)]] <- NA
    DataFile[[paste0(cancer, '_is_first_dx')]] <- NA
  }
  
  # working on cancers
  
  cat('Working on cancers\n')
  
  birth_year <- '34-0.0'
  birth_month <- '52-0.0'
  birth_year <- as.integer(DataFile[[birth_year]])
  birth_month <- as.integer(DataFile[[birth_month]])
  birth_year[birth_year < 1] <- 1900
  birth_month[birth_month < 1] <- 1
  
  birth_date <- lapply(seq_along(birth_year), function(i) {
    as.Date(paste0(birth_year[i], "-", birth_month[i], "-15"), format = "%Y-%m-%d")
  })
  
  NA_date <- as.Date("1900-01-01")
  
  dia_after_enroll <- matrix(100, nrow = length(cancers), ncol = length(age))

  
  # family history
  # age of youngest relative with lung cancer (lung_fh_age) (20111 - illness of siblings) (might have to remove this)
  # this is just if the sibling had cancer...definitely have to edit
  # Convert relevant variables to numeric
  DataFile$X20111.0.0 <- as.numeric(DataFile$X20111.0.0)
  DataFile$X20107.0.0 <- as.numeric(DataFile$X20107.0.0)
  DataFile$X20110.0.0 <- as.numeric(DataFile$X20110.0.0)
  
  DataFile$sibling_lung <- ifelse(DataFile$X20111.0.0 < 0, NA, 
                                  ifelse(DataFile$X20111.0.0 != 3, 0, 1))
  DataFile$lung_fh_age <- DataFile$sibling_lung
  DataFile$fathers_lung <- ifelse(DataFile$X20107.0.0 < 0, NA, 
                                   ifelse(DataFile$X20107.0.0 != 3, 0, 1))
  DataFile$mothers_lung <- ifelse(DataFile$X20110.0.0 < 0, NA, 
                                   ifelse(DataFile$X20110.0.0 != 3, 0, 1))
  DataFile$lung_fh_cnt <- DataFile$fathers_lung + DataFile$mothers_lung + DataFile$sibling_lung
  
  # trials (don't believe that UKB has these)
  DataFile$trial_ph_any <- NA
  DataFile$trial_ph_lung <- NA
  DataFile$lung_is_first_dx <- NA
  
  cat("Female Specific\n")
  
  # Hysterectomy
  DataFile$hystera <- ifelse(!is.na(DataFile$X2824.0.0) & DataFile$X2824.0.0 < 40, 1,
                             ifelse(!is.na(DataFile$X2824.0.0) & DataFile$X2824.0.0 >= 40 & DataFile$X2824.0.0 < 45, 2,
                                    ifelse(!is.na(DataFile$X2824.0.0) & DataFile$X2824.0.0 >= 45 & DataFile$X2824.0.0 < 50, 3,
                                           ifelse(!is.na(DataFile$X2824.0.0) & DataFile$X2824.0.0 >= 50 & DataFile$X2824.0.0 < 55, 4,
                                                  ifelse(!is.na(DataFile$X2824.0.0) & DataFile$X2824.0.0 >= 55, 5, NA)
                                           )
                                    )
                             )
  )
  
  # Divide by 5 to normalize the values between 0 and 1
  DataFile$hystera <- DataFile$hystera / 5

  cat("Hysterectomy done\n")
  

  # Ovaries Removed (UKB 2834 but not in Raw File)
  plco_field <- 'ovariesr_f'
  DataFile[[plco_field]] <- NA
  
  
  cat("Ovaries done\n")
  
  #tuballig - Have you had a tubal ligation? 
  plco_field <- 'tuballig'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(1)
  ukbb_codes <- list(c('Q282', 'Q281', 'Q271'))
  
  surg_len <- 117
  
  for (instance in 0:(surg_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41272.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  cat("Tuballig done\n")

  # bcontr_f
  plco_field <- 'bcontr_f'
  DataFile[[plco_field]] <- NA
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(0), c(1))
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X2784.', instance)]] == old_code & is.na(DataFile[[plco_field]]))
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  cat("bcontr_f done\n")
  
  # age started birth control 
  plco_field <- 'bcontra'
  DataFile[[plco_field]] <- NA
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(0), c(1))
  instances <- c('0.0')
  
  for (instance in instances) {
    idx <- which(DataFile[[paste0('X2794.', instance)]] < 30 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 1
    
    idx <- which(DataFile[[paste0('X2794.', instance)]] >= 30 & DataFile[[paste0('2794-', instance)]] < 40 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 2
    
    idx <- which(DataFile[[paste0('X2794.', instance)]] >= 40 & DataFile[[paste0('2794-', instance)]] <= 50 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 3
    
    idx <- which(DataFile[[paste0('X2794.', instance)]] > 50 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 4
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 4
  
  # Currently taking Hormones
  plco_field <- 'curhorm'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(1, 9)
  ukbb_codes <- list(c(4), c(-1, -3))
  instances <- c('0.0', '1.0', '2.0', '3.0',
                 '0.1', '1.1', '2.1', '3.1',
                 '0.2', '1.2', '2.2', '3.2',
                 '0.3', '1.3', '2.3', '3.3')
  
  for (instance in instances) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X6153.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  # Hormone therapy 
  plco_field <- 'horm_f'
  DataFile[[plco_field]] <- NA
  plco_codes <- c(0, 1, 2)
  ukbb_codes <- list(c(0), c(1), c(-1))
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X2814.', instance)]] == old_code & is.na(DataFile[[plco_field]]))
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  # How many years on HRT 
  plco_field <- 'thorm'
  DataFile[[plco_field]] <- 0
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    field_start <- paste0('X3536.', instance)
    field_end <- paste0('X3546.', instance)
    idx <- which((DataFile[[field_end]] - DataFile[[field_start]]) >= 10 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 1
    
    idx <- which((DataFile[[field_end]] - DataFile[[field_start]]) < 10 & (DataFile[[field_end]] - DataFile[[field_start]]) >= 6 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 2
    
    idx <- which((DataFile[[field_end]] - DataFile[[field_start]]) < 6 & (DataFile[[field_end]] - DataFile[[field_start]]) >= 4 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 3
    
    idx <- which((DataFile[[field_end]] - DataFile[[field_start]]) < 4 & (DataFile[[field_end]] - DataFile[[field_start]]) >= 2 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 4
    
    idx <- which((DataFile[[field_end]] - DataFile[[field_start]]) < 2 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 5
  }
  
  DataFile[[plco_field]] <- 6 - DataFile[[plco_field]]
  DataFile[[plco_field]][DataFile[[plco_field]] == 6] <- 0
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 5
  
  # age at first child 
  plco_field <- 'fchilda'
  DataFile[[plco_field]] <- NA
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    idx <- which(DataFile[[paste0('X3872.', instance)]] < 16 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 1
    
    idx <- which(DataFile[[paste0('X3872.', instance)]] >= 16 & DataFile[[paste0('X3872.', instance)]] < 20 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 2
    
    idx <- which(DataFile[[paste0('X3872.', instance)]] >= 20 & DataFile[[paste0('X3872.', instance)]] < 25 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 3
    
    idx <- which(DataFile[[paste0('X3872.', instance)]] >= 25 & DataFile[[paste0('X3872.', instance)]] < 30 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 4
    
    idx <- which(DataFile[[paste0('X3872.', instance)]] >= 30 & DataFile[[paste0('X3872.', instance)]] < 35 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 5
    
    idx <- which(DataFile[[paste0('X3872.', instance)]] >= 35 & DataFile[[paste0('X3872.', instance)]] < 40 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 6
    
    idx <- which(DataFile[[paste0('X3872.', instance)]] >= 40 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 7
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 7
  
  # How many live births 
  plco_field <- 'livec'
  DataFile[[plco_field]] <- NA
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    idx <- which(DataFile[[paste0('X2734.', instance)]] == 0 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 0
    
    idx <- which(DataFile[[paste0('X2734.', instance)]] == 1 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 1
    
    idx <- which(DataFile[[paste0('X2734.', instance)]] == 2 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 2
    
    idx <- which(DataFile[[paste0('X2734.', instance)]] == 3 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 3
    
    idx <- which(DataFile[[paste0('X2734.', instance)]] == 4 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 4
    
    idx <- which(DataFile[[paste0('X2734.', instance)]] >= 5 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 5
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 5

  # How many miscarriages or abortions
  plco_field <- 'miscar'
  DataFile[[plco_field]] <- NA
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    field_mis <- paste0('X3839.', instance)
    field_abort <- paste0('X3849.', instance)
    total <- DataFile[[field_mis]] + DataFile[[field_abort]]
    
    idx <- which(total == 0 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 0
    
    idx <- which(total == 1 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 1
    
    idx <- which(total >= 2 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 2
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 2
  
  # Ever been pregnant
  plco_field <- 'preg_f'
  DataFile[[plco_field]] <- NA
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(0), c(1))
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    idx <- which(DataFile[[paste0('X2774.', instance)]] == 1 & 
                 DataFile[[paste0('X2734.', instance)]] > 0 & 
                 is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 1
  }
  
  # How many still births
  plco_field <- 'stillb'
  DataFile[[plco_field]] <- NA
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    total <- DataFile[[paste0('X3829.', instance)]]
    idx <- which(total == 0 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 0
    
    idx <- which(total == 1 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 1
    
    idx <- which(total >= 2 & is.na(DataFile[[plco_field]]))
    DataFile[[plco_field]][idx] <- 2
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 2
  
  # Trying to get pregnant unsuccessfully
  cond_len = 213
  plco_field <- 'trypreg'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(1)
  ukbb_codes <- list(c('N970','N971','N972','N973','N974','N978','N979'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  # Tubal Pregnancy
  plco_field <- 'tubal'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(1)
  ukbb_codes <- list(c('O001','O002','O008','O009'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 2
  
  # Menarche
  plco_field <- 'fmenstr'
  DataFile[[plco_field]] <- 0
  instances <- c('0.0', '1.0', '2.0', '3.0')
  
  for (instance in instances) {
    field <- paste0('X2714.', instance)
    idx <- which(DataFile[[field]] < 10 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 1
    
    idx <- which(DataFile[[field]] >= 10 & DataFile[[field]] < 12 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 2
    
    idx <- which(DataFile[[field]] >= 12 & DataFile[[field]] < 14 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 3
    
    idx <- which(DataFile[[field]] >= 14 & DataFile[[field]] < 16 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 4
    
    idx <- which(DataFile[[field]] > 16 & DataFile[[plco_field]] == 0)
    DataFile[[plco_field]][idx] <- 5
  }
  
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 5
  
  # Benign or Fibrocystic Breast Disease
  plco_field <- 'bbd'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('N600', 'N601', 'N602', 'N603', 'N604', 'N608', 'N609'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[[plco_field]][idx] <- plco_codes[i]
      }
    }
  }
  
  # Benign Ovarian Tumor/Cyst
  plco_field <- 'benign_ovcyst'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('D27', 'E282', 'N830', 'N832', 'Q500'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[[plco_field]][idx] <- plco_codes[i]
      }
    }
  }
  
  # Endometriosis
  plco_field <- 'endometriosis'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('N800', 'N801', 'N802', 'N803', 'N804', 'N805', 'N806', 'N808', 'N809'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[[plco_field]][idx] <- plco_codes[i]
      }
    }
  }

  # Uterine Fibroid Tumors (edit later)
  plco_field <- 'uterine_fib'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('D250', 'D251', 'D252', 'D259'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        DataFile[[plco_field]][idx] <- plco_codes[i]
      }
    }
  }
  
  cat("Male specific questions\n")

  plco_field <- 'enlpros_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('N40', 'N400'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  cat("enlpros_f done\n")
  
  plco_field <- 'enlprosa'
  DataFile[[plco_field]] <- 0
  surg_date <- rep(NA_date, length(DataFile[[plco_field]]))
  ukbb_codes <- list(c('N40', 'N400'))
  
  for (instance in 0:(cond_len - 1)) {
    for (old_code in ukbb_codes[[1]]) {
      idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & surg_date == NA_date)
      surg_date[idx] <- as.Date(DataFile[idx, paste0('X41280.0.', instance)], '%Y-%m-%d')
    }
  }
  
  # Convert birth_date to a vector (it's assumed to be already created)
  birth_date_vector <- as.vector(unlist(birth_date))
  
  surg_age <- as.numeric(difftime(surg_date, birth_date_vector, units = "days")) / 365.25
  surg_age[surg_age < 0] <- NA
  idx <- which(surg_age > 0 & surg_age < 30 & DataFile[[plco_field]] == 0)
  DataFile[[plco_field]][idx] <- 1
  idx <- which(surg_age >= 30 & surg_age < 40 & DataFile[[plco_field]] == 0)
  DataFile[[plco_field]][idx] <- 2
  idx <- which(surg_age >= 40 & surg_age < 50 & DataFile[[plco_field]] == 0)
  DataFile[[plco_field]][idx] <- 3
  idx <- which(surg_age >= 50 & surg_age < 60 & DataFile[[plco_field]] == 0)
  DataFile[[plco_field]][idx] <- 4
  idx <- which(surg_age >= 60 & surg_age < 70 & DataFile[[plco_field]] == 0)
  DataFile[[plco_field]][idx] <- 5
  idx <- which(surg_age >= 70 & DataFile[[plco_field]] == 0)
  DataFile[[plco_field]][idx] <- 6
  DataFile[[plco_field]] <- DataFile[[plco_field]] / 6

  
  cat("enlprosa done\n")
  
  plco_field <- 'infpros_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('N410', 'N411', 'N412', 'N413', 'N418', 'N419'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  cat("infpros_f\n")
  
  
  # This one could be improved upon...cannot find it 
  plco_field <- 'infprosa'
  DataFile$infprosa <- NA 
  
  # DataFile[[plco_field]] <- 0
  # surg_date <- rep(NA_date, length(DataFile[[plco_field]]))
  # ukbb_codes <- list(c('N410', 'N411', 'N412', 'N413', 'N418', 'N419'))
  # 
  # for (instance in 0:(cond_len - 1)) {
  #   for (old_code in ukbb_codes[[1]]) {
  #     idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & surg_date == NA_date)
  #     surg_date[idx] <- as.Date(DataFile[idx, paste0('X41280.0.', instance)], '%Y-%m-%d')
  #   }
  # }
  # 
  # # Convert birth_date to a vector (it's assumed to be already created)
  # birth_date_vector <- as.vector(unlist(birth_date))
  # 
  # surg_age <- as.numeric(difftime(surg_date, birth_date_vector, units = "days")) / 365.25
  # surg_age[surg_age < 0] <- NA
  # 
  # DataFile[[plco_field]] <- cut(surg_age, breaks = c(-Inf, 30, 40, 50, 60, 70, Inf), labels = c(1, 2, 3, 4, 5, 6))
  # DataFile[[plco_field]] <- as.numeric(DataFile[[plco_field]]) / 6
  
  
  cat("infprosa done\n")
  
  plco_field <- 'urinate_f'
  DataFile[[plco_field]] <- NA
  
  plco_field <- 'urinatea'
  DataFile[[plco_field]] <- NA
  
  cat("urinate done\n")
  
  # fix surgical age !!!!!
  plco_field <- 'surg_age'
  DataFile[[plco_field]] <- 0
  surg_date <- rep(NA_date, length(DataFile[[plco_field]]))
  ukbb_codes <- list(c('M452', 'M454', 'M611', 'M612', 'M613', 'M614', 'M618', 'M619', 'M621', 'M622', 'M623', 'M624', 'M628', 'M629', 'M651', 'M652', 'M653', 'M654', 'M655', 'M656', 'M671', 'M672', 'M673', 'M674', 'M675', 'M676', 'M678', 'M679', 'M681', 'M682', 'M688', 'M689', 'M683', 'M701', 'M702', 'M703', 'M704', 'M705', 'M706', 'M707', 'M711', 'M712', 'M718', 'M719', 'Z387', 'Z422'))
  
  for (instance in 0:(surg_len - 1)) {
    for (old_code in ukbb_codes[[1]]) {
      idx <- which(DataFile[[paste0('X41272.0.', instance)]] == old_code & surg_date == NA_date)
      surg_date[idx] <- as.Date(DataFile[idx, paste0('X41282.0.', instance)], '%Y-%m-%d')
    }
  }
  
  # Convert birth_date to a vector (it's assumed to be already created)
  birth_date_vector <- as.vector(unlist(birth_date))
  
  surg_age <- as.numeric(difftime(surg_date, birth_date_vector, units = "days")) / 365.25
  surg_age[surg_age < 0] <- NA
  
  # Check if plco_field exists in DataFile and has the correct number of rows
  if (plco_field %in% colnames(DataFile) && nrow(DataFile) == length(surg_age)) {
    DataFile[[plco_field]] <- cut(surg_age, breaks = c(-Inf, 40, 50, 60, 70, Inf), labels = c(1, 2, 3, 4, 5))
    DataFile[[plco_field]] <- as.numeric(DataFile[[plco_field]]) / 5
  } else {
    print("plco_field does not exist in DataFile or has incorrect number of rows.")
  }


  cat("surgical age done\n")

  # s
  plco_field <- 'surg_biopsy'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('M452', 'M454', 'M701', 'M702', 'M703'))
  
  for (instance in 0:(surg_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41272.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  cat("surg_biopsy done\n")
  
  plco_field <- 'surg_prostatectomy'
  DataFile[[plco_field]] <- NA
  

  plco_field <- 'surg_resection'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), 'M651', 'M652', 'M653', 'M654', 'M655', 'M656')
  
  for (instance in 0:(surg_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41272.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  cat("surg_pros and res done\n")
  
  plco_field <- 'vasect_f'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('N171', 'N172', 'N178', 'N179'))
  
  for (instance in 0:(surg_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41272.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
  cat("vasect_f done")
  
  plco_field <- 'vasecta'
  DataFile[[plco_field]] <- 0
  surg_date <- rep(NA_date, length(DataFile[[plco_field]]))
  ukbb_codes <- list(c('N171', 'N172', 'N178', 'N179'))
  
  for (instance in 0:(surg_len - 1)) {
    for (old_code in ukbb_codes[[1]]) {
      idx <- which(DataFile[[paste0('X41272.0.', instance)]] == old_code & surg_date == NA_date)
      surg_date[idx] <- as.Date(DataFile[idx, paste0('X41282.0.', instance)], '%Y-%m-%d')
    }
  }
  
  # Convert birth_date to a vector (it's assumed to be already created)
  birth_date_vector <- as.vector(unlist(birth_date))
  
  surg_age <- as.numeric(difftime(surg_date, birth_date_vector, units = "days")) / 365.25
  surg_age[surg_age < 0] <- NA
  
  # Check if plco_field exists in DataFile and has the correct number of rows
  if (plco_field %in% colnames(DataFile) && nrow(DataFile) == length(surg_age)) {
    DataFile[[plco_field]] <- cut(surg_age, breaks = c(-Inf, 25, 35, 45, Inf), labels = c(1, 2, 3, 4))
    DataFile[[plco_field]] <- as.numeric(DataFile[[plco_field]]) / 4
  } else {
    print("plco_field does not exist in DataFile or has incorrect number of rows.")
  }

  cat("vasecta done\n")
  
# lung cancer
  
  plco_field <- 'lung'
  DataFile[[plco_field]] <- 0
  plco_codes <- c(0, 1)
  ukbb_codes <- list(c(), c('J60', 'J61', 'J628','J634','J635','J638','J64','J660','J668','J670','J672','J674','J676','J677','J678','J679','J680','J681','J682','J683','J684','J688','J689','J690','J691','J698','J700','J701','J702','J703','J704','J708','J709'))
  
  for (instance in 0:(cond_len - 1)) {
    for (i in seq_along(plco_codes)) {
      for (old_code in ukbb_codes[[i]]) {
        idx <- which(DataFile[[paste0('X41270.0.', instance)]] == old_code & DataFile[[plco_field]] == 0)
        if (length(idx) > 0) {
          DataFile[[plco_field]][idx] <- plco_codes[i]
        }
      }
    }
  }
  
DatasetCleaned <- data.frame(
    gender = DataFile$X31.0.0,
    age = DataFile$age,
    raceWh = as.numeric(DataFile$raceWh),
    raceBl = as.numeric(DataFile$raceBl), 
    raceHis = as.numeric(DataFile$raceHis),
    raceAs = as.numeric(DataFile$raceAs), 
    racePI = as.numeric(DataFile$racePI),
    raceAI = as.numeric(DataFile$raceAI),
    #raceMis = as.numeric(DataFile$raceMis),
    edlt8 = as.numeric(DataFile$edlt8),
    ed8t11 = as.numeric(DataFile$ed8t11),
    ed12 = as.numeric(DataFile$ed12),
    edphs = as.numeric(DataFile$edphs),
    edscol = as.numeric(DataFile$edscol),
    edcol = as.numeric(DataFile$edcol),
    edpcol = as.numeric(DataFile$edpcol),
    marmar = as.numeric(DataFile$marmar),
    marwid = as.numeric(DataFile$marwid),
    mardiv = as.numeric(DataFile$mardiv),
    marsep = as.numeric(DataFile$marsep),
    marnvm = as.numeric(DataFile$marnvm),
    #occupat = as.numeric(DataFile$occupat),
    occhmk = as.numeric(DataFile$occhmk),
    occwrk = as.numeric(DataFile$occwrk),
    occune = as.numeric(DataFile$occune),
    occret = as.numeric(DataFile$occret),
    occesl = as.numeric(DataFile$occesl),
    occdis = as.numeric(DataFile$occdis),
    occoth = as.numeric(DataFile$occoth),
    bmi_curr = as.numeric(DataFile$bmi_curr),
    weight20_f = DataFile$weight20_f,
    arthrit_f = DataFile$arthrit_f,
    bronchit_f = DataFile$X22129.0.0,
    liver_comorbidity = DataFile$liver_comorbidity,
    divertic_f = DataFile$divertic_f,
    emphys_f = DataFile$emphys_f,
    gallblad_f = DataFile$gallblad_f,
    hearta_f = DataFile$hearta_f,
    hyperten_f = DataFile$hyperten_f,
    colon_comorbidity = DataFile$colon_comorbidity,
    osteopor_f = DataFile$osteopor_f,
    polyps_f = DataFile$polyps_f,
    stroke_f = DataFile$stroke_f,
    smoked_f = DataFile$smoked_f,
    cig_stat = DataFile$cig_stat,
    cig_stop = DataFile$cig_stop,
    pack_years = DataFile$pack_years,
    asppd = DataFile$asppd,
    ibuppd = DataFile$ibuppd,
    #pros_fh = DataFile$pros_fh,
    diabetes_f = DataFile$diabetes_f,
    #breast_fh = DataFile$breast_fh,
    #colo_fh = DataFile$colo_fh,
    lung_fh_age = DataFile$lung_fh_age,
    lung_fh_cnt = DataFile$lung_fh_cnt,
    lung_fh = DataFile$lung_fh,
    trial_ph_lung = DataFile$trial_ph_lung,
    trial_ph_any = DataFile$trial_ph_any,
    lung_is_first_dx = DataFile$lung_is_first_dx,
    
    hystera = DataFile$hystera,
    ovariesr_f = DataFile$ovariesr_f,
    tuballig = DataFile$tuballig,
    bcontr_f = DataFile$bcontr_f,
    bcontra = DataFile$bcontra,
    curhorm = DataFile$curhorm,
    horm_f = DataFile$horm_f,
    thorm = DataFile$thorm,
    fchilda = DataFile$fchilda,
    livec = DataFile$livec,
    miscar = DataFile$miscar,
    preg_f = DataFile$preg_f,
    stillb = DataFile$stillb,
    trypreg = DataFile$trypreg,
    tubal = DataFile$tubal,
    fmenstr = DataFile$fmenstr,
    bbd = DataFile$bbd,
    benign_ovcyst = DataFile$benign_ovcyst,
    endometriosis = DataFile$endometriosis,
    uterine_fib = DataFile$uterine_fib,
    
    # Male Specific
    enlpros_f = DataFile$enlpros_f,
    enlprosa = DataFile$enlprosa,
    infpros_f = DataFile$infpros_f,
    infprosa = DataFile$infprosa,
    urinate_f = DataFile$urinate_f,
    urinatea = DataFile$urinatea,
    surg_age = DataFile$surg_age,
    surg_biopsy = DataFile$surg_biopsy,
    surg_prostatectomy = DataFile$surg_prostatectomy,
    surg_resection = DataFile$surg_resection,
    vasect_f = DataFile$vasect_f,
    vasecta = DataFile$vasecta,
    
    lung = DataFile$lung

)
  
  return(DatasetCleaned)
  
}

 cleanedData <- processUKBData(UKBiobank)
 
```


Write data files to .csv

```{r}

writeDataFiles <- function(data) {
  male_only_columns <- c('enlpros_f', 'enlprosa', 'infpros_f', 'infprosa',
                         'urinate_f', 'urinatea', 'surg_age', 'surg_biopsy',
                         'surg_prostatectomy', 'surg_resection', 'vasect_f',
                         'vasecta', 'mbreast', 'pros')
  female_only_columns <- c('hystera', 'ovariesr_f', 'tuballig', 'bcontr_f',
                           'bcontra', 'curhorm', 'horm_f', 'thorm', 'fchilda',
                           'livec', 'miscar', 'preg_f', 'stillb', 'trypreg',
                           'tubal', 'fmenstr', 'bbd', 'benign_ovcyst',
                           'endometriosis', 'uterine_fib', 'breast', 'endo',
                           'ovar')
  
  male_data <- data[data$gender == 0, !(names(data) %in% female_only_columns)]
  write.csv(male_data, 'male_UKBdata.csv', row.names = FALSE)
  
  female_data <- data[data$gender == 1, !names(data) %in% male_only_columns]
  write.csv(female_data, 'female_UKBdata.csv', row.names = FALSE)
}

writeDataFiles(cleanedData)



```

See if the columns match

```{r}

# Read the CSV files
female_UKB <- read.csv("/Users/teresanguyen/Downloads/CleaningLungData/Data Files/female_UKBdata.csv", as.is = TRUE)
female_PLCO <- read.csv("/Users/teresanguyen/Downloads/CleaningLungData/Data Files/female_lung_data.csv", as.is = TRUE)

# Get column names that are in female_UKB but not in female_PLCO
missing_in_PLCO <- setdiff(names(female_UKB), names(female_PLCO))

# Get column names that are in female_PLCO but not in female_UKB
missing_in_UKB <- setdiff(names(female_PLCO), names(female_UKB))

if (length(missing_in_PLCO) > 0) {
  cat("Columns missing in female_PLCO:", paste(missing_in_PLCO, collapse = ", "), "\n")
} else {
  cat("All column names in female_UKB are present in female_PLCO.\n")
}

if (length(missing_in_UKB) > 0) {
  cat("Columns missing in female_UKB:", paste(missing_in_UKB, collapse = ", "), "\n")
} else {
  cat("All column names in female_PLCO are present in female_UKB.\n")

}

```

```{r}

# Read the CSV files
male_UKB <- read.csv("/Users/teresanguyen/Downloads/CleaningLungData/Data Files/female_UKBdata.csv", as.is = TRUE)
male_PLCO <- read.csv("/Users/teresanguyen/Downloads/CleaningLungData/Data Files/female_lung_data.csv", as.is = TRUE)

# Get column names that are in female_UKB but not in female_PLCO
missing_in_PLCO <- setdiff(names(male_UKB), names(male_PLCO))

# Get column names that are in female_PLCO but not in female_UKB
missing_in_UKB <- setdiff(names(male_PLCO), names(male_UKB))

if (length(missing_in_PLCO) > 0) {
  cat("Columns missing in male_PLCO:", paste(missing_in_PLCO, collapse = ", "), "\n")
} else {
  cat("All column names in male_UKB are present in male_PLCO.\n")
}

if (length(missing_in_UKB) > 0) {
  cat("Columns missing in male_UKB:", paste(missing_in_UKB, collapse = ", "), "\n")
} else {
  cat("All column names in male_PLCO are present in male_UKB.\n")

}

```