---
title: "NHIS Subsections"
output: html_notebook
---

Read in the data.

```{r}

NHIS_Male <- read.csv("/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/male_NHISdata.csv")

NHIS_Female <- read.csv("/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/female_NHISdata.csv")


```

70% NHIS 

```{r}

# Set the threshold value
threshold <- 0.70

# Function to find columns with enough data and always include specified columns
find_columns_with_data <- function(data, threshold, always_include) {
  non_na_counts <- colSums(!is.na(data))
  total_rows <- nrow(data)
  # Calculate the proportion of non-NA data for each column
  sufficient_data_cols <- non_na_counts / total_rows >= threshold
  # Ensure specified columns are always included
  sufficient_data_cols[always_include] <- TRUE
  # Return the names of the columns that meet the criteria or are specified to always include
  names(data)[sufficient_data_cols]
}

# Use the function to find columns for male and female datasets, always including "lung"
columns_with_data_male <- find_columns_with_data(NHIS_Male, threshold, "lung")
columns_with_data_female <- find_columns_with_data(NHIS_Female, threshold, "lung")

# Print the columns with data for verification
print(columns_with_data_male)
print(columns_with_data_female)

# Filter each dataset based on its own specific columns
filtered_male <- NHIS_Male[, columns_with_data_male, drop = FALSE]
filtered_female <- NHIS_Female[, columns_with_data_female, drop = FALSE]

# Save the filtered datasets to new CSV files
write.csv(filtered_male, "/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/male_filtered_70_NHIS.csv", row.names = FALSE)
write.csv(filtered_female, "/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/female_filtered_70_NHIS.csv", row.names = FALSE)


```

30% NHIS 

```{r}

# Set the threshold value
threshold2 <- 0.30

# Use the function to find columns for male and female datasets, always including "lung"
columns_with_data_male2 <- find_columns_with_data(NHIS_Male, threshold2, "lung")
columns_with_data_female2 <- find_columns_with_data(NHIS_Female, threshold2, "lung")

# Print the columns with data for verification
print(columns_with_data_male2)
print(columns_with_data_female2)

# Filter each dataset based on its own specific columns
filtered_male2 <- NHIS_Male[, columns_with_data_male2, drop = FALSE]
filtered_female2 <- NHIS_Female[, columns_with_data_female2, drop = FALSE]

# Save the filtered datasets to new CSV files
write.csv(filtered_male2, "/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/male_filtered_30_NHIS.csv", row.names = FALSE)
write.csv(filtered_female2, "/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/female_filtered_30_NHIS.csv", row.names = FALSE)

```

```{r}

chosen_NHIS_male <- NHIS_Male[, c("age", "gender", "raceWh", "raceHis", "raceAs", "raceAI", "raceMis", "edlt8", "ed8t11", "ed12", "edphs", "edscol", "edcol", "edpcol", "marmar", "marwid", "mardiv", "marsep", "marnvm", "occwrk", "occune", "occret", "occoth", "bmi_curr", "arthrit_f", "bronchit_f", "diabetes_f", "emphys_f", "hearta_f", "hyperten_f", "liver_comorbidity", "stroke_f", "smoked_f", "cig_stat", "ibup", "lung_fh_age", "lung_fh_cnt", "trial_ph_any", "lung"), drop = FALSE]

chosen_NHIS_female <- NHIS_Female[, c("age", "gender", "raceWh", "raceHis", "raceAs", "raceAI", "raceMis", "edlt8", "ed8t11", "ed12", "edphs", "edscol", "edcol", "edpcol", "marmar", "marwid", "mardiv", "marsep", "marnvm", "occwrk", "occune", "occret", "occoth", "bmi_curr", "arthrit_f", "bronchit_f", "diabetes_f", "emphys_f", "hearta_f", "hyperten_f", "liver_comorbidity", "stroke_f", "smoked_f", "cig_stat", "ibup", "lung_fh_age", "lung_fh_cnt", "trial_ph_any", "lung"), drop = FALSE]

write.csv(chosen_NHIS_male, "/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/male_filtered_chosen_NHIS.csv", row.names = FALSE)
write.csv(chosen_NHIS_female, "/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/female_filtered_chosen_NHIS.csv", row.names = FALSE)

```


```{r}

# Count of NA, 1, and 0 in the "lung" column for the male dataset
male_lung_counts <- table(filtered_male$lung, useNA = "ifany")
male_lung_counts["NA"] <- sum(is.na(filtered_male$lung))  # Explicitly count NAs

# Count of NA, 1, and 0 in the "lung" column for the female dataset
female_lung_counts <- table(filtered_female$lung, useNA = "ifany")
female_lung_counts["NA"] <- sum(is.na(filtered_female$lung))  # Explicitly count NAs

# Print the counts for both datasets
print("Counts for the lung column in the male dataset:")
print(male_lung_counts)

print("Counts for the lung column in the female dataset:")
print(female_lung_counts)


```


After removing all surveys less than 18 years old.

```{r}

NHISFemaleImput <- read.csv("/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/female_filtered_70_NHIS_imputed.csv")

dim(NHISFemaleImput)

NHISFemaleBefore <- read.csv("/Users/teresanguyen/Documents/Lung-Statistical-Biopsy/Data Files/female_filtered_70_NHIS.csv")

dim(NHISFemaleBefore)

```
